import React, { useState } from 'react';
import { FileText, Sparkles, Download, Cpu, Zap, WifiOff, TrendingUp, TrendingDown, Minus } from 'lucide-react';
import { generateWeeklyReport, getActiveProvider, OLLAMA_MODEL, type AIProvider } from '../lib/ai';
import { useAppContext } from '../context/AppContext';
import type { DriftLevel } from '../types';

interface Props {
  avgDrift: number;
  level: DriftLevel;
  typingHistory: number[];
}

const FALLBACK_REPORTS = [
  "This week showed moderate stress indicators with a Drift Index averaging in the declining range. Journal entries reflect work-related pressure and sleep disruption. Typing patterns suggest elevated cognitive load mid-week. Recommendation: prioritise sleep hygiene and schedule a check-in session within the next 7 days.",
  "Overall mental health indicators this week are stable with minor fluctuations. Mood data shows resilience and consistent self-awareness through journaling. No critical risk signals detected. Recommendation: maintain current wellness practices and consider adding a daily 5-minute mindfulness routine.",
  "Significant stress escalation detected this week. Multiple high-drift sessions and negative sentiment patterns in journal entries suggest burnout risk. Typing hesitation rates increased 40% from baseline. Immediate recommendation: reduce workload where possible and book a priority appointment with your psychiatrist.",
];

const ProviderIcon = ({ p }: { p: AIProvider }) =>
  p === 'ollama' ? <Cpu style={{ width: 11, height: 11 }} /> :
  p === 'gemini' ? <Zap style={{ width: 11, height: 11 }} /> :
  <WifiOff style={{ width: 11, height: 11 }} />;

export const WeeklyReport: React.FC<Props> = ({ avgDrift, typingHistory }) => {
  const { journals, moodLog } = useAppContext();
  const [report, setReport]   = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [provider, setProvider] = useState<AIProvider>('mock');
  const [ms, setMs]           = useState<number | null>(null);
  const [generated, setGenerated] = useState<Date | null>(null);

  const avgMood = moodLog.length
    ? moodLog.slice(0, 7).reduce((s, e) => s + e.value, 0) / Math.min(moodLog.length, 7)
    : 5;

  const generate = async () => {
    setLoading(true);
    const p = await getActiveProvider();
    setProvider(p);
    const t0 = Date.now();
    try {
      const text = await generateWeeklyReport(
        avgDrift, avgMood,
        journals.slice(0, 5).map(j => ({ title: j.title, mood: j.mood, content: j.content.slice(0, 200) })),
        typingHistory
      );
      setReport(text || FALLBACK_REPORTS[Math.floor(avgDrift / 34)]);
      setMs(Date.now() - t0);
      setGenerated(new Date());
    } catch {
      setReport(FALLBACK_REPORTS[Math.floor(avgDrift / 34)]);
    }
    setLoading(false);
  };

  const providerColor = provider === 'ollama' ? '#10b981' : provider === 'gemini' ? '#60a5fa' : '#f59e0b';
  const providerLabel = provider === 'ollama' ? `Ollama · ${OLLAMA_MODEL}` : provider === 'gemini' ? 'Gemini 1.5 Flash' : 'Smart fallback';

  const trendIcon = avgDrift > 65
    ? <TrendingUp  style={{ width: 14, height: 14, color: '#ef4444' }} />
    : avgDrift > 35
    ? <Minus       style={{ width: 14, height: 14, color: '#f59e0b' }} />
    : <TrendingDown style={{ width: 14, height: 14, color: '#10b981' }} />;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }} className="animate-fade-in">

      {/* Header */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{
            width: 40, height: 40, borderRadius: 12,
            background: 'var(--accent-dim)', border: '1px solid var(--accent-border)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <FileText style={{ width: 18, height: 18, color: 'var(--accent)' }} />
          </div>
          <div>
            <p style={{ fontSize: 15, fontWeight: 600, color: 'var(--text-1)' }}>Weekly AI Report</p>
            <p style={{ fontSize: 12, color: 'var(--text-2)' }}>Full mental health summary generated by AI</p>
          </div>
        </div>
      </div>

      {/* Stats summary */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10 }}>
        {[
          { label: 'Avg Drift',  value: Math.round(avgDrift), unit: '/100', color: avgDrift > 65 ? '#ef4444' : avgDrift > 35 ? '#f59e0b' : '#10b981', icon: trendIcon },
          { label: 'Avg Mood',   value: avgMood.toFixed(1),   unit: '/10',  color: '#a78bfa', icon: null },
          { label: 'Journals',   value: journals.length,      unit: '',     color: '#60a5fa', icon: null },
        ].map(s => (
          <div key={s.label} style={{
            background: 'var(--surface)', border: '1px solid var(--border)',
            borderRadius: 12, padding: '14px 16px', textAlign: 'center',
          }}>
            <p style={{ fontSize: 11, color: 'var(--text-3)', marginBottom: 4 }}>{s.label}</p>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 4 }}>
              {s.icon}
              <span style={{ fontSize: 22, fontWeight: 700, color: s.color }}>{s.value}</span>
              <span style={{ fontSize: 11, color: 'var(--text-3)' }}>{s.unit}</span>
            </div>
          </div>
        ))}
      </div>

      {/* Generate button */}
      {!report && !loading && (
        <div style={{
          background: 'var(--surface)', border: '1px solid var(--border)',
          borderRadius: 16, padding: 32, textAlign: 'center',
        }}>
          <Sparkles style={{ width: 32, height: 32, color: 'var(--accent)', margin: '0 auto 12px' }} />
          <p style={{ fontSize: 14, fontWeight: 500, color: 'var(--text-1)', marginBottom: 6 }}>
            Generate your weekly mental health report
          </p>
          <p style={{ fontSize: 12, color: 'var(--text-3)', marginBottom: 20, maxWidth: 320, margin: '0 auto 20px' }}>
            AI analyses your Drift Index, mood logs, journal entries, and typing stress to produce a clinical-grade summary.
          </p>
          <button onClick={generate} className="btn-primary" style={{ gap: 8 }}>
            <Sparkles style={{ width: 15, height: 15 }} />
            Generate Report
          </button>
        </div>
      )}

      {/* Loading skeleton */}
      {loading && (
        <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
            <Sparkles style={{ width: 14, height: 14, color: 'var(--accent)', animation: 'spin-slow 2s linear infinite' }} />
            <span style={{ fontSize: 13, color: 'var(--text-2)' }}>
              {provider === 'ollama' ? `${OLLAMA_MODEL} is writing your report…` : 'Generating report…'}
            </span>
          </div>
          {[100, 90, 95, 75, 85].map((w, i) => (
            <div key={i} style={{
              height: 11, borderRadius: 6, background: 'var(--border-2)',
              width: `${w}%`, marginBottom: 10,
              animation: 'pulse-red 1.5s ease-in-out infinite',
              animationDelay: `${i * 0.1}s`,
            }} />
          ))}
        </div>
      )}

      {/* Report */}
      {report && !loading && (
        <div className="animate-fade-in" style={{
          background: 'var(--surface)', border: '1px solid var(--border)',
          borderRadius: 16, padding: 24,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <ProviderIcon p={provider} />
              <span style={{ fontSize: 11, color: providerColor, fontWeight: 500 }}>{providerLabel}</span>
              {ms && <span style={{ fontSize: 10, color: 'var(--text-3)' }}>· {ms}ms</span>}
            </div>
            <div style={{ display: 'flex', gap: 8 }}>
              <button onClick={generate} style={{
                display: 'flex', alignItems: 'center', gap: 4,
                padding: '5px 10px', borderRadius: 8,
                background: 'var(--surface-2)', border: '1px solid var(--border)',
                color: 'var(--text-2)', fontSize: 11, cursor: 'pointer',
              }}>
                <Sparkles style={{ width: 10, height: 10 }} /> Regenerate
              </button>
              <button onClick={() => {
                const blob = new Blob([`NEWRON WEEKLY MENTAL HEALTH REPORT\n${generated?.toLocaleDateString()}\n\n${report}`], { type: 'text/plain' });
                const a = document.createElement('a'); a.href = URL.createObjectURL(blob);
                a.download = `newron-report-${Date.now()}.txt`; a.click();
              }} style={{
                display: 'flex', alignItems: 'center', gap: 4,
                padding: '5px 10px', borderRadius: 8,
                background: 'var(--accent-dim)', border: '1px solid var(--accent-border)',
                color: 'var(--accent)', fontSize: 11, cursor: 'pointer',
              }}>
                <Download style={{ width: 10, height: 10 }} /> Export
              </button>
            </div>
          </div>

          <div style={{
            padding: '16px 18px', borderRadius: 12,
            background: 'var(--surface-2)', border: '1px solid var(--border)',
            marginBottom: 12,
          }}>
            <p style={{ fontSize: 13, color: 'var(--text-1)', lineHeight: 1.8 }}>{report}</p>
          </div>

          {generated && (
            <p style={{ fontSize: 10, color: 'var(--text-3)' }}>
              Generated {generated.toLocaleString()} · Based on {journals.length} journal entries, {moodLog.length} mood logs, {typingHistory.length} typing tests
            </p>
          )}
        </div>
      )}
    </div>
  );
};
